### ISSUE TITLE
不得其解

### ISSUE THREAD

**Issue by YangZhaocool** [bigoceans/TencentVideoAutoCheck#2]
日志里面记录的都是成功
为什么我实际的账号的签到的状态没有变呢 
cookie是我自己账号的

**Comment by miiiiiint** [comment]
因为腾讯限制除了客户端签到，其他平台都得刷验证码，另外，腾讯视频用了ssl加密技术，不授信用户证书，你不root也是抓不了包的，再另外，就算这样还是会时不时跳验证码
